---
title: "parallel.Rmd"
author: "Matt Jones"
date: "2023-10-25"
output: html_document
---

This is the parallel lesson. Update the parallel lesson.

Stuff to be added.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(palmerpenguins)
library(dplyr)
library(tidyr)
```

# Load our data

```{r}
bill_length <- penguins %>% 
  select(species, bill_length_mm) %>% 
  drop_na() %>% 
  as.data.frame()
head(bill_length)
```

# Loop for a bootstrap

```{r}
trials <- 3000
res <- data.frame()
system.time({
  trial <- 1
  while (trial <= trials) {
    index <- sample(100, 100, replace=TRUE)
    result1 <- glm(bill_length[index,1]~bill_length[index,2], family=binomial(logit))
    r <- coefficients(result1)
    res <- rbind(res, r)
    trial <- trial + 1
}
})
```

```{r}
boot_fx <- function(trial) {
    index <- sample(100, 100, replace=TRUE)
    result1 <- glm(bill_length[index,1]~bill_length[index,2], family=binomial(logit))
    r <- coefficients(result1)
    res <- rbind(data.frame(), r)
}

trials <- seq(1, trials)
system.time({
  results <- lapply(trials, boot_fx)
})
```


# Parellize with mclappy

```{r}
library(parallel)
numCores <- detectCores()
numCores
```

```{r}
system.time({
  res_mca <- mclapply(trials, boot_fx, mc.cores = numCores)
})
```


# Foreach as alooping model

```{r}
library(foreach)
foreach (i=1:3) %do% {
  sqrt(i)
}
```
```{r}
library(doParallel)
registerDoParallel(numCores)
foreach (i=1:3, .combine=rbind) %dopar% {
  sqrt(i)
}
```
```{r}
num_trials <- 3000
system.time({
  r <- foreach(icount(num_trials), .combine=rbind) %dopar% {
    index <- sample(100, 100, replace=TRUE)
    result1 <- glm(bill_length[index,1]~bill_length[index,2], family=binomial(logit))
    coefficients(result1)
  }
})
```

```{r}
stopImplicitCluster()
```


# Future and furrr

```{r}
library(future)
plan(multisession)
f <- future({
  cat("Hello world!\n")
  6.28
})

v <- value(f)
v
```

```{r}
plan(multisession)

download_data <- function() {
  Sys.sleep(0.5)
  return(c(1,2,3))
}

run_model <- function(d) {
  Sys.sleep(0.5)
  return(42)
}

model_result <- future({
  d <- download_data()
  result <- run_model(d)
  result
})

while(!resolved(model_result)) {
  cat("Waiting for model to complete...\n")
  Sys.sleep(0.2)
  cat("Do some. more work, like refresh another graph or something...\n")
}

value(model_result)
```

## Now with purrr and furrr

```{r}
library(purrr)
system.time({
  res_purr <- map(trials, boot_fx)
})
```
```{r}
library(furrr)
plan(multisession, workers=80)
system.time({
  res_furrr <- future_map(trials, boot_fx, .options = furrr_options(seed = TRUE))
})
```

Finis.